# Generated by Django 4.0.1 on 2022-01-11 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'connection',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=30, null=True)),
                ('JObTitles', models.TextField(max_length=300)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=12)),
                ('IsActive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'master',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Birthdate', models.DateField(auto_created=True, default='1999-08-01')),
                ('FullName', models.CharField(default='', max_length=30, null=True)),
                ('JobTitle', models.CharField(default='', max_length=30, null=True)),
                ('Mobile', models.CharField(default='', max_length=10, null=True)),
                ('RefID', models.CharField(default='', max_length=30)),
                ('Gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=10, null=True)),
                ('Country', models.CharField(default='', max_length=10, null=True)),
                ('State', models.CharField(default='', max_length=25, null=True)),
                ('City', models.CharField(default='', max_length=25, null=True)),
                ('Address', models.TextField(default='', max_length=150, null=True)),
                ('Img', models.FileField(upload_to='images')),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.master')),
                ('department', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='todoapp.department')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deadline', models.DateTimeField(auto_created=True)),
                ('Title', models.TextField(max_length=150)),
                ('Tags', models.TextField(max_length=150)),
                ('Description', models.TextField(max_length=150)),
                ('Iscomplete', models.BooleanField(default=False)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.master')),
            ],
            options={
                'db_table': 'ToDO',
            },
        ),
        migrations.CreateModel(
            name='ToDOparticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.connection')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.todo')),
            ],
            options={
                'db_table': 'ToDoParticipant',
            },
        ),
        migrations.CreateModel(
            name='ToDoMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.profile')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.todo')),
            ],
            options={
                'db_table': 'ToDoMember',
            },
        ),
        migrations.CreateModel(
            name='connectionRequet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.master')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.profile')),
            ],
            options={
                'db_table': 'connectionRequet',
            },
        ),
        migrations.AddField(
            model_name='connection',
            name='Master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.master'),
        ),
        migrations.AddField(
            model_name='connection',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.profile'),
        ),
    ]
