# Generated by Django 4.0.1 on 2022-01-11 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(upload_to='media', verbose_name='My Photo')),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.master')),
            ],
        ),
    ]
