# Generated by Django 4.0.1 on 2022-01-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
