# Generated by Django 4.0.1 on 2022-01-17 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_delete_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Img',
        ),
        migrations.CreateModel(
            name='profile_pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.FileField(null=True, upload_to='images')),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.master')),
            ],
            options={
                'db_table': 'profile_pic',
            },
        ),
    ]
